name: Publish Docker image

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get commit tag
        id: get_commit_tag
        run: echo "::set-output name=tag::$(git describe --tags --exact-match ${{ github.sha }} || echo '')"

      - name: Use commit tag for image tagging
        id: use_commit_tag
        run: echo "::set-output name=tag::${{ steps.get_commit_tag.outputs.tag }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            imyashkale/homepage:${{ steps.use_commit_tag.outputs.tag }}
            imyashkale/homepage:latest
