name: Publish Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        run: docker build -t imyashkale/homepage:${{ github.sha }} .

      - name: Tag Docker image as git latest commit
        run: docker tag imyashkale/homepage:${{ github.sha }} imyashkale/homepage:latest

      - name: Push the Docker image
        run: docker push imyashkale/homepage:${{ github.sha }} && docker push imyashkale/homepage:latest